CREATE DATABASE IF NOT EXISTS notice1
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE notice1;

CREATE TABLE IF NOT EXISTS notice(
	no INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT "sequence",
	NoticeTitle VARCHAR(32),
	NoticeDesc VARCHAR(500),
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SET @COUNT=0;
UPDATE notice SET notice.no=@COUNT:=@COUNT+1;