CREATE DATABASE IF NOT EXISTS state1
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE state1;

CREATE TABLE IF NOT EXISTS state(
	no INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT "sequence",
	StateTitle VARCHAR(50)
);